### ISSUE TITLE
Specify initial split

### ISSUE THREAD

**Issue by cpa-level-it** [wannabegeek/ng2-split-pane#2]
It would be great to be able to specify an initial split between the component.

I was able to do this via CSS using the following rules (in an angular-cli project)

```css

:host /deep/ .v-outer .left-component {
    width: calc(80% - 4px);
}

:host /deep/ .v-outer .right-component {
    width: calc(20% - 4px);
}

```

But having a parameter like `primary-component-minsize` would be a nice addition I think.
Great lib by the way.
